name: stat_git_workspaces
description: Status information for group of Git workspaces
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  ansix: ^0.0.9-prerelease
  args: ^2.4.2
  cli_completion: ^0.3.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
